/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Beacon(props: any) {
  const { nodes, materials } = useGLTF('/models/beacon.glb');
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  );
}

useGLTF.preload('/models/beacon.glb');
